In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\ML Byself\Deep Learning\customer_churn_dataset-testing-master.csv")

In [3]:
df

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,Female,33,12,6,21,Basic,Quarterly,947,14,1
64370,64371,37,Male,6,1,5,22,Standard,Annual,923,9,1
64371,64372,25,Male,39,14,8,30,Premium,Monthly,327,20,1
64372,64373,50,Female,18,19,7,22,Standard,Monthly,540,13,1
64373,64374,52,Female,45,15,9,25,Standard,Monthly,696,22,1

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()
# Convert categorical columns to numerical
df['Gender'] = le.fit_transform(df['Gender'])
df['Subscription Type'] = le.fit_transform(df['Subscription Type'])
df['Contract Length'] = le.fit_transform(df['Contract Length'])

In [6]:
df

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,0,25,14,4,27,0,1,598,9,1
1,2,41,0,28,28,7,13,2,1,584,20,0
2,3,47,1,27,10,2,29,1,0,757,21,0
3,4,35,1,9,12,5,17,1,2,232,18,0
4,5,53,0,58,24,9,2,2,0,533,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,0,33,12,6,21,0,2,947,14,1
64370,64371,37,1,6,1,5,22,2,0,923,9,1
64371,64372,25,1,39,14,8,30,1,1,327,20,1
64372,64373,50,0,18,19,7,22,2,1,540,13,1
64373,64374,52,0,45,15,9,25,2,1,696,22,1

In [7]:
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [9]:
input_data = df.iloc[:, :-1]  
output_data = df.iloc[:, -1]

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
ss=StandardScaler()

In [12]:
ss.fit_transform(input_data)

array([[-1.7320239 , -1.43420211, -0.93482484, ...,  0.01104616,
         0.21840769, -0.75232377],
       [-1.73197009, -0.0697304 , -0.93482484, ...,  0.01104616,
         0.16474168,  0.52106473],
       [-1.73191628,  0.36115541,  1.06971912, ..., -1.22347696,
         0.82790017,  0.63682733],
       ...,
       [ 1.73191628, -1.21875921,  1.06971912, ...,  0.01104616,
        -0.82041283,  0.52106473],
       [ 1.73197009,  0.57659831, -0.93482484, ...,  0.01104616,
        -0.0039229 , -0.28927341],
       [ 1.7320239 ,  0.72022691, -0.93482484, ...,  0.01104616,
         0.59406972,  0.75258992]])

In [13]:
input_data = pd.DataFrame(ss.fit_transform(input_data), columns=input_data.columns)

In [14]:
input_data

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,-1.732024,-1.434202,-0.934825,-0.409100,-0.122526,-0.449807,1.114538,-1.225188,0.011046,0.218408,-0.752324
1,-1.731970,-0.069730,-0.934825,-0.233642,1.465424,0.513590,-0.467000,1.223248,0.011046,0.164742,0.521065
2,-1.731916,0.361155,1.069719,-0.292128,-0.576225,-1.092072,1.340472,-0.000970,-1.223477,0.827900,0.636827
3,-1.731862,-0.500616,1.069719,-1.344876,-0.349375,-0.128674,-0.015132,-0.000970,1.245569,-1.184575,0.289540
4,-1.731809,0.792041,-0.934825,1.520939,1.011724,1.155855,-1.709637,1.223248,-1.223477,-0.030756,0.289540
...,...,...,...,...,...,...,...,...,...,...,...
64369,1.731809,0.217527,-0.934825,0.058789,-0.349375,0.192458,0.436736,-1.225188,1.245569,1.556225,-0.173511
64370,1.731862,-0.356988,1.069719,-1.520334,-1.597050,-0.128674,0.549703,1.223248,-1.223477,1.464226,-0.752324
64371,1.731916,-1.218759,1.069719,0.409705,-0.122526,0.834723,1.453439,-0.000970,0.011046,-0.820413,0.521065
64372,1.731970,0.576598,-0.934825,-0.818502,0.444599,0.513590,0.549703,1.223248,0.011046,-0.003923,-0.289273
64373,1.732024,0.720227,-0.934825,0.760621,-0.009101,1.155855,0.888604,1.223248,0.011046,0.594070,0.752590

In [22]:
from sklearn.model_selection import train_test_split

In [19]:
#to check input node
input_data.shape

(64374, 11)

In [23]:
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.2,random_state=42)

In [29]:
x_train.shape

(51499, 11)

In [37]:
print(input_data.columns)  # Verify the number of features

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction'],
      dtype='object')

In [24]:
 import tensorflow

In [38]:
input_data = input_data.astype("float32")

In [39]:
from keras.layers import Dense
from keras.models import Sequential

In [40]:
ann=Sequential()

In [41]:
ann.add(Dense(10,input_dim=input_data.shape[1],activation="relu"))
ann.add(Dense(6,activation="relu"))
ann.add(Dense(2,activation="relu"))
ann.add(Dense(1,activation="sigmoid"))

C:\Users\kunal\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [42]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [43]:
ann.fit(x_train,y_train,batch_size=1000,epochs=10)

Epoch 1/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5892 - loss: 0.6523
Epoch 2/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7920 - loss: 0.5945
Epoch 3/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.5332
Epoch 4/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.4614
Epoch 5/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8606 - loss: 0.3769
Epoch 6/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8703 - loss: 0.3168
Epoch 7/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8740 - loss: 0.2966
Epoch 8/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8785 - loss: 0.2853
Epoch 9/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8802 - loss: 0.2787
Epoch 10/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8859 - loss: 0.2660

In [54]:
pr1=ann.predict(x_train)
pr_data1=[]
for i in pr1:
    if i[0] >0.5:
        pr_data1.append(1)
    else:
        pr_data1.append(0)

1610/1610 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step

In [47]:
pr=ann.predict(x_test)

403/403 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [50]:
pr_data=[]
for i in pr:
    if i[0] >0.5:
        pr_data.append(1)
    else:
        pr_data.append(0)

In [51]:
pr_data

[0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 ...]

In [44]:
from sklearn.metrics import accuracy_score

In [52]:
accuracy_score(y_test,pr_data)#testing accuracy

0.8946796116504855

In [56]:
accuracy_score(y_train,pr_data1)#training

0.8885609429309307

In [57]:
x_test

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
15476,-0.899227,0.935670,1.069719,-0.701530,1.011724,-0.449807,-1.257769,1.223248,0.011046,0.360239,1.099878
34666,0.133427,-1.003316,1.069719,-0.292128,1.692274,-0.449807,-1.370736,-0.000970,1.245569,0.344906,-0.636561
50474,0.984089,1.653813,-0.934825,1.637911,0.217749,0.513590,-0.128099,-0.000970,1.245569,-0.870246,-1.678425
7984,-1.302388,0.792041,1.069719,0.877593,0.104324,0.834723,-1.144802,-0.000970,-1.223477,-0.053756,-0.289273
20227,-0.643566,-0.716059,1.069719,1.403967,-1.143350,0.513590,-0.241066,-0.000970,-1.223477,-1.169242,1.099878
...,...,...,...,...,...,...,...,...,...,...,...
15815,-0.880985,0.002084,1.069719,1.403967,0.217749,-0.128674,-0.354033,-0.000970,-1.223477,-0.118921,0.405302
23037,-0.492354,1.438370,-0.934825,-1.812764,0.898299,-1.092072,0.210802,1.223248,1.245569,1.598391,-1.446899
55566,1.258101,0.720227,-0.934825,1.053051,-0.916500,-0.128674,1.227505,-0.000970,1.245569,1.264895,-1.099612
22749,-0.507852,-1.577831,-0.934825,1.403967,1.125149,-0.449807,0.323769,1.223248,-1.223477,0.942899,0.868353
31651,-0.028816,0.217527,-0.934825,0.936079,0.671449,-1.092072,-0.015132,-0.000970,0.011046,-0.145754,-1.562662

In [63]:
y_test

15476    0
34666    0
50474    1
7984     0
20227    0
        ..
15815    0
23037    0
55566    1
22749    0
31651    0
Name: Churn, Length: 12875, dtype: int64

In [64]:
given_input = np.array([
    -0.899227, 0.935670, 1.069719, -0.701530, 1.011724,
    -0.449807, -1.257769, 1.223248, 0.011046, 0.360239, 1.099878
]).reshape(1, -1)

In [65]:
prediction = ann.predict(given_input)
predicted_class = 1 if prediction[0][0] > 0.5 else 0

predicted_class

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

0

In [67]:
predicted_class

0

In [68]:
ann.save("churn_model.h5")
np.save("scaler.npy", ss)

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.